branch-defaults:
  master:
    environment: civiwikiorg-dev
  website:
    environment: civiwikiorg-dev
global:
  application_name: civiwiki.org
  default_ec2_keyname: civiwiki_ec2
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
